name: Run script
on:
  push: 
    branches: main

jobs:
   run-script:
     runs-on: linux
     steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: ejecuta script
          run: ./test.sh
